# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 23:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(max_length=100)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2018, 1, 25, 23, 46, 30, 901094, tzinfo=utc))),
                ('max_tickets', models.IntegerField()),
                ('tickets_sold', models.IntegerField()),
            ],
        ),
    ]
