# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180125_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='max_tickets',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='tickets_sold',
            field=models.IntegerField(default=0),
        ),
    ]
