# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 23:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ApeClassSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2018, 1, 25, 23, 46, 30, 888392, tzinfo=utc))),
                ('num_sessions', models.IntegerField(help_text='Number of Sessions')),
                ('max_enrollment', models.IntegerField(help_text='Max number of students')),
                ('ape_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.ApeClass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ClassMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ape_class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_membership', to='classes.ApeClassSession')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.Person')),
                ('classes', models.ManyToManyField(related_name='students', through='classes.ClassMember', to='classes.ApeClassSession')),
            ],
            bases=('people.person',),
        ),
        migrations.AddField(
            model_name='classmember',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_membership', to='classes.Student'),
        ),
    ]
