# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20180125_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apeclass',
            options={'verbose_name': 'Ape Class', 'verbose_name_plural': 'Ape Classes'},
        ),
        migrations.AlterModelOptions(
            name='apeclasssession',
            options={'verbose_name': 'Ape Class Session', 'verbose_name_plural': 'Ape Class Sessions'},
        ),
        migrations.AddField(
            model_name='apeclass',
            name='bio',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
