# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20180126_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apeclasssession',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
    ]
