# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20180126_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='apeclass',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apeclasssession',
            name='enrollment_closes',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='apeclasssession',
            name='enrollment_opens',
            field=models.DateField(null=True),
        ),
    ]
