# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCarouselItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('link_id', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('link_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, choices=[('home', 'Home'), ('classes', 'Classes'), ('events', 'Events'), ('people', 'People'), ('about', 'About')], null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('draft', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PageToWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_to_widgets', to='pages.Page')),
            ],
            options={
                'ordering': ['page', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BannerWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Widget')),
                ('link_id', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('link_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
                'abstract': False,
            },
            bases=('pages.widget', models.Model),
        ),
        migrations.CreateModel(
            name='EventFocusWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Widget')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
            options={
                'abstract': False,
            },
            bases=('pages.widget',),
        ),
        migrations.CreateModel(
            name='EventsWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Widget')),
                ('display_type', models.CharField(blank=True, choices=[('gallery', 'Cover Gallery'), ('row_focus', 'Row')], default='gallery', max_length=100, null=True)),
                ('events', models.ManyToManyField(blank=True, related_name='events_widgets', to='events.Event')),
            ],
            options={
                'verbose_name': 'group of events',
                'verbose_name_plural': 'groups of events',
            },
            bases=('pages.widget',),
        ),
        migrations.CreateModel(
            name='ImageCarouselWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Widget')),
            ],
            options={
                'verbose_name': 'carousel of big images',
                'verbose_name_plural': 'carousels of big images',
            },
            bases=('pages.widget',),
        ),
        migrations.CreateModel(
            name='TextWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Widget')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'block of text',
                'verbose_name_plural': 'blocks of text',
            },
            bases=('pages.widget',),
        ),
        migrations.AddField(
            model_name='pagetowidget',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_to_widgets', to='pages.Widget'),
        ),
        migrations.AddField(
            model_name='page',
            name='widgets_base',
            field=models.ManyToManyField(related_name='pages', through='pages.PageToWidget', to='pages.Widget'),
        ),
        migrations.AlterUniqueTogether(
            name='pagetowidget',
            unique_together=set([('page', 'widget')]),
        ),
        migrations.AddField(
            model_name='imagecarouselitem',
            name='carousel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.ImageCarouselWidget'),
        ),
    ]
