# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('classes', '0002_auto_20180222_1100'),
        ('events', '0002_auto_20180222_1100'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personfocuswidget',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
        migrations.AddField(
            model_name='peoplewidget',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='people_widgets', to='people.Person'),
        ),
        migrations.AddField(
            model_name='peoplewidget',
            name='source_house_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.HouseTeam'),
        ),
        migrations.AlterUniqueTogether(
            name='pagetowidget',
            unique_together=set([('page', 'widget')]),
        ),
        migrations.AddField(
            model_name='imagecarouselitem',
            name='carousel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.ImageCarouselWidget'),
        ),
        migrations.AddField(
            model_name='eventswidget',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='events_widgets', to='events.Event'),
        ),
        migrations.AddField(
            model_name='eventfocuswidget',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='bannerwidget',
            name='link_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='apeclassfocuswidget',
            name='ape_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.ApeClass'),
        ),
        migrations.AddField(
            model_name='apeclasseswidget',
            name='ape_classes',
            field=models.ManyToManyField(blank=True, related_name='ape_classes_widgets', to='classes.ApeClass'),
        ),
    ]
