# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20180130_1251'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Widget')),
                ('display_type', models.CharField(blank=True, choices=[('gallery', 'Cover Gallery'), ('row_focus', 'Row')], default='gallery', max_length=100, null=True)),
                ('people', models.ManyToManyField(blank=True, related_name='people_widgets', to='people.Person')),
            ],
            options={
                'verbose_name': 'group of people',
                'verbose_name_plural': 'groups of people',
            },
            bases=('pages.widget',),
        ),
        migrations.CreateModel(
            name='PersonFocusWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Widget')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person')),
            ],
            options={
                'abstract': False,
            },
            bases=('pages.widget',),
        ),
    ]
