# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pages.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('pages', '0002_peoplewidget_personfocuswidget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApeClassesWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Widget')),
                ('display_type', models.CharField(blank=True, choices=[('gallery', 'Cover Gallery'), ('row_focus', 'Row')], default='gallery', max_length=100, null=True)),
                ('ape_classes', models.ManyToManyField(blank=True, related_name='ape_classes_widgets', to='classes.ApeClass')),
            ],
            options={
                'verbose_name': 'group of ape classes',
                'verbose_name_plural': 'groups of ape classes',
            },
            bases=('pages.widget',),
        ),
        migrations.CreateModel(
            name='ApeClassFocusWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Widget')),
                ('ape_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.ApeClass')),
            ],
            options={
                'abstract': False,
            },
            bases=('pages.widget',),
        ),
        migrations.AlterModelOptions(
            name='imagecarouselitem',
            options={'ordering': ['sort_order'], 'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.AlterField(
            model_name='imagecarouselitem',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Time at which this item will turn off', null=True),
        ),
        migrations.AlterField(
            model_name='imagecarouselitem',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Time at which this item will turn on', null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='widgets_base',
            field=pages.fields.SortedManyToManyField(related_name='pages', through='pages.PageToWidget', to='pages.Widget'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Time at which this widget will turn off', null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Time at which this widget will turn on', null=True),
        ),
    ]
