# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20180203_1211'),
        ('pages', '0003_auto_20180203_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplewidget',
            name='source_house_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.HouseTeam'),
        ),
    ]
