# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import pages.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_peoplewidget_source_house_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='background_end_color',
            field=pages.fields.ColorField(blank=True, help_text='Also used as fade color for background image if specified (default is dominant image color)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='background_gradient',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='page',
            name='background_start_color',
            field=pages.fields.ColorField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='buy_button_color',
            field=pages.fields.ColorField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='buy_button_text_color',
            field=pages.fields.ColorField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='text_color',
            field=pages.fields.ColorField(blank=True, max_length=10, null=True),
        ),
    ]
