# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 20:14
from __future__ import unicode_literals

from django.db import migrations
import pages.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20180204_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='textwidget',
            name='text_color',
            field=pages.fields.ColorField(blank=True, max_length=10),
        ),
    ]
