# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_textwidget_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='apeclasseswidget',
            name='class_type',
            field=models.CharField(blank=True, choices=[('IMPROV', 'Improv'), ('SKETCH', 'Sketch'), ('ACTING', 'Acting')], default='gallery', max_length=100, null=True),
        ),
    ]
