# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20180304_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiowidget',
            name='audio_file',
            field=models.FileField(help_text='Allowed type - .mp3, .ogg', upload_to='audio'),
        ),
    ]
