# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_apeclasseswidget_class_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventswidget',
            name='upcoming_events',
            field=models.BooleanField(default=False),
        ),
    ]
