# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_eventswidget_upcoming_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventswidget',
            name='upcoming_events_window',
            field=models.IntegerField(blank=True, help_text='Number of days in future for which events will display.', null=True),
        ),
    ]
