# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-29 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20180321_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventswidget',
            name='display_type',
            field=models.CharField(blank=True, choices=[('gallery', 'Cover Gallery'), ('row_focus', 'Row'), ('list', 'List')], default='gallery', max_length=100, null=True),
        ),
    ]
