# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 21:04
from __future__ import unicode_literals

import audiofield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_eventswidget_upcoming_events_window'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Widget')),
                ('audio_file', audiofield.fields.AudioField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', upload_to='audio_files')),
            ],
            options={
                'abstract': False,
            },
            bases=('pages.widget',),
        ),
    ]
