# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-05 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20180405_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, choices=[('home', 'Home'), ('classes', 'Classes'), ('shows', 'Shows'), ('faculty', 'Faculty'), ('talent', 'Talent'), ('houseteams', 'House Teams'), ('apetv', 'Ape TV'), ('hype', 'Hype')], null=True),
        ),
    ]
