# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_audiowidget_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Widget')),
                ('video_file', models.FileField(upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('pages.widget',),
        ),
    ]
