# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 05:00
from __future__ import unicode_literals

import audiofield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_videowidget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiowidget',
            name='audio_file',
            field=audiofield.fields.AudioField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='videowidget',
            name='video_file',
            field=models.FileField(help_text='Allowed type - .mp4, .ogg', upload_to='videos'),
        ),
    ]
