# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20180204_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerwidget',
            name='image',
            field=models.ImageField(upload_to='images/banner/'),
        ),
    ]
