# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-23 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_houseteamfocuswidget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('video_file', models.FileField(help_text='Allowed type - .mp4, .ogg', upload_to='videos')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFocusWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Widget')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Video')),
            ],
            options={
                'abstract': False,
            },
            bases=('pages.widget',),
        ),
        migrations.CreateModel(
            name='VideosWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Widget')),
                ('display_type', models.CharField(blank=True, choices=[('gallery', 'Cover Gallery'), ('row_focus', 'Row')], default='gallery', max_length=100, null=True)),
                ('video_clips', models.ManyToManyField(blank=True, related_name='video_widgets', to='pages.Video')),
            ],
            options={
                'verbose_name': 'group of videos',
                'verbose_name_plural': 'groups of videos',
            },
            bases=('pages.widget',),
        ),
    ]
