# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-23 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_video_videofocuswidget_videoswidget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videowidget',
            name='widget_ptr',
        ),
        migrations.DeleteModel(
            name='VideoWidget',
        ),
    ]
