# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-30 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_video_videofocuswidget_videoswidget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoswidget',
            old_name='video_clips',
            new_name='videos',
        ),
    ]
