# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-05 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20180430_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressClippingWidget',
            fields=[
                ('textwidget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.TextWidget')),
                ('author', models.CharField(max_length=100)),
                ('external_link', models.URLField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('pages.textwidget',),
        ),
    ]
