# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20180206_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='buy_button_color',
            new_name='button_color',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='buy_button_text_color',
            new_name='button_text_color',
        ),
    ]
