# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-05 17:23
from __future__ import unicode_literals

from django.db import migrations
import pages.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_pressclippingwidget'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressclippingwidget',
            name='background_color',
            field=pages.fields.ColorField(blank=True, max_length=10),
        ),
    ]
