# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20180207_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apeclassfocuswidget',
            name='ape_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.ApeClass'),
        ),
    ]
