# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 23:25
from __future__ import unicode_literals

from django.db import migrations
import pages.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20180212_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='nav_bar_color',
            field=pages.fields.ColorField(blank=True, help_text='This will also set the color of widget headers', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='nav_bar_text_color',
            field=pages.fields.ColorField(blank=True, max_length=10, null=True),
        ),
    ]
