# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20180210_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquareCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='SquareError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SquarePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='square_payments.SquareCustomer')),
            ],
        ),
        migrations.AddField(
            model_name='squareerror',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='square_payments.SquarePayment'),
        ),
    ]
