# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square_payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='squarepayment',
            name='nonce',
            field=models.CharField(default='asirao49a3ghoe', max_length=200),
            preserve_default=False,
        ),
    ]
