# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square_payments', '0002_squarepayment_nonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='squarepayment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
