# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('square_payments', '0003_squarepayment_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='squarepayment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='squareerror',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='square_payments.SquarePayment'),
        ),
    ]
