# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-20 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('square_payments', '0004_auto_20180220_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squareerror',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='squarecustomer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='squarecustomer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='squarepayment',
            name='error_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='squarepayment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='square_payments.SquareCustomer'),
        ),
        migrations.DeleteModel(
            name='SquareError',
        ),
    ]
