# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square_payments', '0005_auto_20180220_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squarepayment',
            name='error_message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
