# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20180220_1348'),
        ('classes', '0009_auto_20180220_1838'),
        ('square_payments', '0006_auto_20180220_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='squarepayment',
            name='purchase_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.ApeClass'),
        ),
        migrations.AddField(
            model_name='squarepayment',
            name='purchase_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
