# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180210_1939'),
        ('square_payments', '0008_auto_20180221_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='squarecustomer',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
