# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('square_payments', '0009_squarecustomer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squarecustomer',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='square_purchaser', to='accounts.UserProfile'),
        ),
    ]
