# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180221_2004'),
        ('events', '0008_auto_20180220_1348'),
        ('square_payments', '0010_auto_20180221_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='squarecustomer',
            name='shows',
            field=models.ManyToManyField(related_name='shows', through='accounts.EventAttendee', to='events.Event'),
        ),
    ]
