# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square_payments', '0011_squarecustomer_shows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squarecustomer',
            name='shows',
            field=models.ManyToManyField(related_name='attendees', through='accounts.EventAttendee', to='events.Event'),
        ),
    ]
