# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 23:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_admin', models.BooleanField(default=False)),
                ('ape_admin', models.BooleanField(default=False)),
                ('last_activity_time', models.DateTimeField(blank=True, help_text='Time stamp of last activity through the Ape UI.', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
