# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='source',
            field=models.CharField(default='admin', max_length=10),
        ),
    ]
