# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20180209_1419'),
        ('accounts', '0002_auto_20180129_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_paid', models.BooleanField(default=False)),
                ('ape_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_membership', to='classes.ApeClass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_membership', to='accounts.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='classes',
            field=models.ManyToManyField(related_name='students', through='accounts.ClassMember', to='classes.ApeClass'),
        ),
    ]
