# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180222_1145'),
        ('accounts', '0003_auto_20180222_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shows',
            field=models.ManyToManyField(related_name='attendees', through='accounts.EventAttendee', to='events.Event'),
        ),
    ]
