# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-11 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180209_1408'),
        ('accounts', '0003_auto_20180209_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_paid', models.BooleanField(default=False)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendance', to='accounts.UserProfile')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_attendance', to='events.Event')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shows',
            field=models.ManyToManyField(related_name='shows', through='accounts.EventAttendee', to='events.Event'),
        ),
    ]
