# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-11 03:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180210_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattendee',
            name='has_paid',
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 2, 11, 3, 39, 13, 603894, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
