# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-26 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_shows'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('ticket', models.FileField(upload_to='tickets')),
                ('event_attendee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='accounts.EventAttendee')),
            ],
        ),
    ]
