# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-26 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='pdf',
            field=models.FileField(null=True, upload_to='tickets'),
        ),
    ]
