# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180221_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventattendee',
            name='attendee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_attendance', to='square_payments.SquareCustomer'),
        ),
    ]
