# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-08 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_classregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='num_attendees',
            field=models.IntegerField(default=1),
        ),
    ]
