# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180221_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='public',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='source',
        ),
    ]
