# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-17 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_classmember_purchase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmember',
            name='has_paid',
        ),
    ]
