# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('teaches', models.BooleanField(default=False)),
                ('performs', models.BooleanField(default=True)),
                ('house_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.HouseTeam')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
    ]
