# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 20:00
from __future__ import unicode_literals

from django.db import migrations


HOUSE_TEAMS = [
    {'name': 'bigTiny'},
    {'name': 'Cashmere'},
    {'name': 'Merv'},
    {'name': 'Snakemelter'},    
]


PEOPLE = [
    {
        'first_name': 'Ben',
        'last_name': 'Campbell',
        'bio': '',
        'image': '',
        'teaches': False,
        'performs': True,
        'house_team': 'Merv'
    },
    {
        'first_name': 'Katie',
        'last_name': 'Kester',
        'bio': '',
        'image': '',
        'teaches': False,
        'performs': True,
        'house_team': 'Merv'
    },
    {
        'first_name': 'Michael',
        'last_name': 'Knackstedt',
        'bio': '',
        'image': '',
        'teaches': True,
        'performs': True,
        'house_team': 'Merv'
    },
    {
        'first_name': 'Natalie',
        'last_name': 'Haddad',
        'bio': '',
        'image': '',
        'teaches': False,
        'performs': True,
        'house_team': 'Merv'
    },
    {
        'first_name': 'Zach',
        'last_name': 'Calvert',
        'bio': '',
        'image': '',
        'teaches': False,
        'performs': True,
        'house_team': 'Merv'
    },
    {
        'first_name': 'Adrien',
        'last_name': 'Warner',
        'bio': '',
        'image': '',
        'teaches': False,
        'performs': True,
        'house_team': 'Cashmere'
    },
    {
        'first_name': 'Ali',
        'last_name': 'Marocco',
        'bio': '',
        'image': '',
        'teaches': False,
        'performs': True,
        'house_team': 'Cashmere'
    },
    {
        'first_name': 'Anne',
        'last_name': 'Zander',
        'bio': '',
        'image': '',
        'teaches': False,
        'performs': True,
        'house_team': 'Cashmere'
    },
    {
        'first_name': 'Courtney',
        'last_name': 'Rainwater',
        'bio': '',
        'image': '',
        'teaches': False,
        'performs': True,
        'house_team': 'Cashmere'
    },
    {
        'first_name': 'Lauren',
        'last_name': 'Sinner',
        'bio': '',
        'image': '',
        'teaches': False,
        'performs': True,
        'house_team': 'Cashmere'
    },
    {
        'first_name': 'Michael',
        'last_name': 'Schoenfelder',
        'bio': '',
        'image': '',
        'teaches': True,
        'performs': True,
        'house_team': 'Cashmere'
    },
    {
        'first_name': 'Marcus',
        'last_name': 'Garrett',
        'bio': '',
        'image': '',
        'teaches': False,
        'performs': True,
        'house_team': 'bigTiny'
    },
    {
        'first_name': 'Mike',
        'last_name': 'Carlip',
        'bio': '',
        'image': '',
        'teaches': False,
        'performs': True,
        'house_team': 'bigTiny'
    },
    {
        'first_name': 'Pat',
        'last_name': 'Donaldson',
        'bio': '',
        'image': '',
        'teaches': False,
        'performs': True,
        'house_team': 'bigTiny'
    },
    {
        'first_name': 'Christa',
        'last_name': 'Helms',
        'bio': '',
        'image': '',
        'teaches': False,
        'performs': True,
        'house_team': 'Snakemelter'
    },
    {
        'first_name': 'Michael',
        'last_name': 'Morgan',
        'bio': '',
        'image': '',
        'teaches': False,
        'performs': True,
        'house_team': 'bigTiny'
    },
    {
        'first_name': 'Brianna',
        'last_name': 'Nunez-Webb',
        'bio': '',
        'image': '',
        'teaches': False,
        'performs': True,
        'house_team': 'Snakemelter'
    },
    {
        'first_name': 'Tony',
        'last_name': 'Cohen',
        'bio': '',
        'image': '',
        'teaches': False,
        'performs': True,
        'house_team': 'Snakemelter'
    },
    {
        'first_name': 'Michael',
        'last_name': 'Zimmer',
        'bio': '',
        'image': '',
        'teaches': True,
        'performs': True,
        'house_team': 'Snakemelter'
    },
    {
        'first_name': 'Chris',
        'last_name': 'Caniglia',
        'bio': '',
        'image': '',
        'teaches': True,
        'performs': True,
        'house_team': ''
    },
    {
        'first_name': 'Alissa',
        'last_name': 'Jessup',
        'bio': '',
        'image': '',
        'teaches': True,
        'performs': True,
        'house_team': ''
    },
]

PAGES = [
    {
        'name': 'Home',
        'slug': 'Home',
    },
    {
        'name': 'Classes',
        'slug': 'Classes'
    },
    {
        'name': 'Shows',
        'slug': 'Shows'
    },
    {
        'name': 'Faculty',
        'slug': 'Faculty'
    },
    {
        'name': 'Performers',
        'slug': 'Performers'
    },
    {
        'name': 'Media',
        'slug': 'Media'
    },
]


def create_apes(apps, schema_editor):
    Person = apps.get_model('people', 'Person')
    HouseTeam = apps.get_model('people', 'HouseTeam')

    for house_team_dict in HOUSE_TEAMS:
        HouseTeam.objects.get_or_create(
            name=house_team_dict['name']
        )

    for person_dict in PEOPLE:
        Person.objects.get_or_create(
            first_name=person_dict['first_name'],
            last_name=person_dict['last_name'],
            teaches=person_dict['teaches'],
            performs=person_dict['performs'],
            house_team=HouseTeam.objects.filter(name=person_dict['house_team']).first()
        )


def create_pages(apps, schema_editor):
    Page = apps.get_model('pages', 'Page')

    for page_dict in PAGES:
        Page.objects.get_or_create(
            name=page_dict['name'],
            slug=page_dict['slug']
        )


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_apes),
        migrations.RunPython(create_pages)
    ]
