# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_widget_width'),
        ('people', '0003_person_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseteam',
            name='image_carousel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.ImageCarouselWidget'),
        ),
    ]
