# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20180130_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['first_name'], 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
    ]
