# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20180130_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='image',
            new_name='headshot',
        ),
    ]
