# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_videowidget'),
        ('people', '0005_auto_20180203_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='videos',
            field=models.ManyToManyField(to='pages.VideoWidget'),
        ),
    ]
