# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-23 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_remove_houseteam_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseteam',
            name='show_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
