# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-05 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_person_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='videos',
            field=models.ManyToManyField(blank=True, to='pages.VideoWidget'),
        ),
    ]
