# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-23 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_houseteamfocuswidget'),
        ('people', '0006_houseteam_show_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseteam',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.BannerWidget'),
        ),
    ]
