# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20180204_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='house_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performers', to='people.HouseTeam'),
        ),
    ]
