# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20180205_1510'),
        ('people', '0008_auto_20180206_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseteam',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.BannerWidget'),
        ),
    ]
