# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-23 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_video_videofocuswidget_videoswidget'),
        ('people', '0008_auto_20180423_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseteam',
            name='video_clips',
            field=models.ManyToManyField(blank=True, to='pages.Video'),
        ),
        migrations.AddField(
            model_name='person',
            name='video_clips',
            field=models.ManyToManyField(blank=True, to='pages.Video'),
        ),
    ]
