# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-23 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20180423_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseteam',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='person',
            name='videos',
        ),
    ]
