# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-15 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20180211_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseteam',
            name='videos',
            field=models.ManyToManyField(blank=True, to='pages.VideoWidget'),
        ),
        migrations.AlterField(
            model_name='person',
            name='videos',
            field=models.ManyToManyField(blank=True, to='pages.VideoWidget'),
        ),
    ]
