# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0004_auto_20180130_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('class_type', models.CharField(choices=[('IMPROV', 'Improv'), ('SKETCH', 'Sketch'), ('ACTING', 'Acting')], max_length=50)),
            ],
            options={
                'verbose_name': 'Ape Class',
                'verbose_name_plural': 'Ape Classes',
            },
        ),
        migrations.CreateModel(
            name='ApeClassSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True)),
                ('num_sessions', models.IntegerField(help_text='Number of Sessions')),
                ('max_enrollment', models.IntegerField(help_text='Max number of students')),
                ('enrollment_opens', models.DateField(null=True)),
                ('enrollment_closes', models.DateField(null=True)),
                ('ape_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.ApeClass')),
            ],
            options={
                'verbose_name': 'Ape Class Session',
                'verbose_name_plural': 'Ape Class Sessions',
            },
        ),
        migrations.CreateModel(
            name='ClassMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ape_class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_membership', to='classes.ApeClassSession')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.Person')),
                ('classes', models.ManyToManyField(related_name='students', through='classes.ClassMember', to='classes.ApeClassSession')),
            ],
            bases=('people.person',),
        ),
        migrations.AddField(
            model_name='classmember',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_membership', to='classes.Student'),
        ),
        migrations.AddField(
            model_name='apeclasssession',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
    ]
