# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_houseteam_banner'),
        ('classes', '0003_auto_20180209_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmember',
            name='ape_class_session',
        ),
        migrations.AddField(
            model_name='apeclass',
            name='enrollment_closes',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apeclass',
            name='enrollment_opens',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apeclass',
            name='max_enrollment',
            field=models.IntegerField(default=12, help_text='Max number of students'),
        ),
        migrations.AddField(
            model_name='apeclass',
            name='num_sessions',
            field=models.IntegerField(default=4, help_text='Number of Sessions'),
        ),
        migrations.AddField(
            model_name='apeclass',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apeclass',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Person'),
        ),
        migrations.AddField(
            model_name='classmember',
            name='ape_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_membership', to='classes.ApeClass'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(related_name='students', through='classes.ClassMember', to='classes.ApeClass'),
        ),
    ]
