# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-25 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20180222_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apeclass',
            name='class_type',
            field=models.CharField(choices=[('IMPROV', 'Improv'), ('SKETCH', 'Sketch'), ('ACTING', 'Acting'), ('WORKSHOP', 'Workshop')], max_length=50),
        ),
    ]
