# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20180209_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apeclasssession',
            name='ape_class',
        ),
        migrations.RemoveField(
            model_name='apeclasssession',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='ApeClassSession',
        ),
    ]
