# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-05 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20180225_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apeclass',
            name='enrollment_closes',
        ),
        migrations.RemoveField(
            model_name='apeclass',
            name='enrollment_opens',
        ),
        migrations.AddField(
            model_name='apeclass',
            name='class_length',
            field=models.IntegerField(default=2, help_text='Length of one class session, in hours.'),
        ),
    ]
