# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-21 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20180304_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='apeclass',
            name='registration_open',
            field=models.BooleanField(default=True),
        ),
    ]
