# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20180207_1153'),
        ('classes', '0005_auto_20180209_1419'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassMember',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
