# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-02 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_apeclass_registration_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='apeclass',
            name='deposit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='apeclass',
            name='students_registered',
            field=models.IntegerField(default=0),
        ),
    ]
