# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-10 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20180209_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apeclass',
            name='active',
        ),
    ]
