# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_remove_apeclass_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='apeclass',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
