# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_apeclass_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apeclass',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
