# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 19:45
from __future__ import unicode_literals

from django.db import migrations


EVENTS = [
    {
        'name': 'Thursday Soiree',
        'bio': 'Add bio here',
        'ticket_price': '5.00',
    },
    {
        'name': 'Standing Upright',
        'bio': 'Add bio here',
        'ticket_price': '10.00',
    },
    {
        'name': 'Night Cheese',
        'bio': 'Add bio here',
        'ticket_price': '5.00',
    },
]


def create_events(apps, schema_editor):
    Event = apps.get_model('events', 'Event')

    for event_dict in EVENTS:
        Event.objects.get_or_create(
            name=event_dict['name'],
            bio=event_dict['bio'],
            ticket_price=event_dict['ticket_price']
        )


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180222_1100'),
    ]

    operations = [
        migrations.RunPython(create_events)
    ]
