# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_peoplewidget_personfocuswidget'),
        ('events', '0002_auto_20180129_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.BannerWidget'),
        ),
    ]
