# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-06 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180222_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_tickets',
            field=models.IntegerField(default=20, null=True),
        ),
    ]
