# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bio',
            field=models.TextField(),
        ),
    ]
