# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-07 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180406_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='videos',
        ),
    ]
