# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180201_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time']},
        ),
    ]
