# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-11 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20180207_1153'),
        ('events', '0005_auto_20180209_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='videos',
            field=models.ManyToManyField(blank=True, null=True, to='pages.VideoWidget'),
        ),
    ]
